### ISSUE TITLE
Size of histogram is miscalculated, too big overflows it's parent

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_range_limit#111]
The JS drawing the histogram need sto be told it's width/height. There is some JS code in blacklight_range_limit that tries to calculate what it should be based on how much space is available. 

This is currently failing in some circumstances. And you get something like this:

![date_range_overflow](https://user-images.githubusercontent.com/149304/67964618-f300cd80-fbd6-11e9-8dcc-3bb3eadb3b24.jpeg)

For me, this happens whenever I am loading a page with an _existing_ range limit applied, so it opens with that facet section _starting out open_. Clicking on the facet section header to close and then re-open the section -- actually triggers a recalculation/redisplay and corrects it's size. 

For me, on MacOS Chrome, this is pretty reproducible. Pretty much every time I load a page with an existing facet limit, it happens. However, on the very same app, other people on other browser/platform combos sometimes don't see the problem. 

@pmulak on Slack also independently observed the problem, and said it reproduced on Firefox Chrome. Here where I am, we have one Windows Chrome that _does_ reproduce it, and one that doens't. I think it's not actually browser-specific, but just hard to reproduce for as of yet mysterious reasons. 

Somehow at the point the JS code is trying to determine the on-screen layout space available for the chart, it is not succesfully getting the right value. I previously spent some time investigating and was not able to figure it out, it's some creaky code (that i probably wrote originally many years ago). But I am now going to spend more time, and will try to leave notes here.

**Comment by jrochkind** [comment]
Oh darnit, when I try debugging in JS (with debugger statements or console.log), what had been reproducible on my computer, stops reproducing. I'd say it's a timing-related race-condition of some kind. Not sure if I can get it to show up on my computer now, which is a problem for diagnosing!

**Comment by jrochkind** [comment]
My own app in which I'm reproducing the problem loads it's JS with `defer: true`. @pmulak, I am wondering if same is true for you?

I am not entirely sure if removing that makes problem go away; of course, we'd like to be able to do that.

**Comment by jrochkind** [comment]
OK, yes. 

1. We have to tell `flot` the height/width dimensions to render the plot

2. We have a variety of hooks in JS code to try to resize it on browser window resize, on facet collapse open/close, etc. 

3. But for the initial display of a date range in a facet collapsible that is _already_ open (because it already had a selection so defaults to open), it just does it as soon as it finds it -- in a `Blacklight.onload`. Which is basically `DOMContentLoaded` plus turbolinks events.  There is logic to wait until the area has a non-0 width, because of previous cases where it was 'too early' and it had a 0 width. 

4. But there are some cases DOMContentLoaded fires when the sidebar area doesn't really have it's "resting" size yet, but doesn't have a 0 width, it seems to have a  has a _full viewport width_ size. 
    * **This may be ONLY** if you have your <script> tag set to defer and/or async, or it may be a lot more likely if you have defer/async. I was unable to reproduce without defer/async. I'm not sure if BL by default generates with defer and/or async, I think not? But it is a reasonable thing to want to do that shouldn't break things. 
  * How likely this is to happen or whether it can may depend on how many layout reflows happen in BL loading and the particular DOM, so it's not too shocking if a new BL version with refactored DOM/JS/CSS would change it. 

It's not entirely clear to me how to fix this or the best way to minimize it. 

* If there were a way to subscribe to an event for "layout/reflow done", that'd be the right time to draw/size the chart. But it's really never "done", and there is no web api to subscribe to "layout/reflow" events (perhaps cause it would risk infinite loop as your handler could cause one!)

* If there was a way to *not* have to tell flot the exact size, but just get it to generate a `canvas` that was 100% of parent an automatically reflowed, that'd be great. Or something other than flot? Not sure if there is, something other than flot would of course require some major rewriting, I am not pursuing either of these. 

* if the range facet didn't start out open even if it there was a selected range limit, everything would work right -- by the time you can see it, it probably has the right size, and there's a draw/resize triggered on facet expand already. Unclear how we could make this so, or if it'd be desirable?

* In my experiments while the `DOMContentLoaded` event is sometimes too early, body.onload never is. 
  * However, Blacklight.onload gives us a nice turbolinks-friendly way to hook into DOMContentLoaded, we don't have a pre-built way without reinventing the wheel to make it load+turbolinks instead. 
  * And `load` is probably sometimes _way too late_. It doesn't fire until all images have loaded. 

* We can add an _additional_ hook, it keeps doing everything it's doing, but ALSO does a chart resize on `body.onload`. I did this by adding at line 109:
        window.addEventListener('load', function(event) {
          $(".chart_js").each(function(i, container) {
            redrawPlot($(container));
          });
        });

  That SEEMED to fix up _my_ use case, I was unable to reproduce the problem once adding it. I don't _think_ it'll create any problems -- although it is an additional 'resize' operation, telling flot to redraw the chart when it may not be needed. (Could actually be extended with a conditional to only do it if the size seems to have changed?)

  I can't promise it will fix or work right in _all_ use cases. This is all pretty hacky, and really needs a whole different approach probably, but that's outside my available time/energy right now. 

Any thoughts or feedback from anyone else welcome!

**Comment by jrochkind** [comment]
And here's a really hacky workaround that works in my own local app, with no changes to blacklight_range_limit. 

We want to trigger a chart redraw on `body.onload`. But all that code is locked within blacklight_range_limit closure. But blacklight_range_limit will already respond to a `shown.bs.collapse` event with a chart redraw/resize. 

So we can send a fake `shown.bs.collapse` on the collapsible element for the facet(s) that contain the blacklight_range_limit chart. In my case, the div that has a bootstrap collapsible for that facet winds up with id `facet-year_facet_isim`

So in my local code:

```js
window.addEventListener('load', function(event) {
  $("#facet-year_facet_isim").trigger("shown.bs.collapse");
});
```

Seems to solve the problem for me, doesn't seem to cause any problems even with the facet has no pre-existing limit and begins collapsed. VERY HACKY.

**Comment by pghorpade** [comment]
Thanks @jrochkind , I am going to try some of the workaround solutions you provided.

**Comment by dkinzer** [comment]
Just confirming that @jrochkind hack works for us though we used `$("#facet-pub_date_sort").trigger("shown.bs.collapse");`

**Comment by jrochkind** [comment]
As JS and chart rendering is now entirely differnet implementation from when this ticket was written, this ticket is no longer relevant.
