### ISSUE TITLE
edge x-axis labels go out of container and are hidden

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_range_limit#131]
Probably related to flot upgrade. 

## blacklight_range_limit 7.1.0:
![Screenshot 2019-12-16 15 01 13](https://user-images.githubusercontent.com/149304/70939252-d8af7180-2015-11ea-9304-20220889ab10.png)

## blacklight_range_limit 7.4.0:
![Screenshot 2019-12-16 15 06 54](https://user-images.githubusercontent.com/149304/70939199-c2091a80-2015-11ea-9382-5bffc64b8e6c.png)

(I also note here that some of the text color seems to have changed, not sure if that was intentional?)

**Comment by ggeisler** [comment]
> (I also note here that some of the text color seems to have changed, not sure if that was intentional?)

@jrochkind Can you be more specific about what text color you think has changed?

**Comment by jrochkind** [comment]
@ggeisler sorry, I missed that question. The x-axis labels in 7.1.0 screenshot above are a lighter grey; in 7.4.0 screenshot are a darker grey or black, not sure which.
