### ISSUE TITLE
Ensure `BlacklightRangeLimit::ControllerOverride` gets injected after `Blacklight::Catalog`

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight_range_limit#134]
If not, it can cause an ordering issue. Seen in https://github.com/sul-dlss/exhibits/pull/1646

**Comment by barmintor** [comment]
Fixed in https://github.com/projectblacklight/blacklight_range_limit/commit/418d1ef9f4f4534831691c3847179f2f4fc631af see also #153
