### ISSUE TITLE
Range limit constraint does not take into account blacklight config

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight_range_limit#168]
Our blacklight application has two separate blacklight range fields that are not part of the same configuration or even on the same controller.  However when we switch between the controller paths the application will render all the range limit param constraints even if that controller should not know about all the range limit fields that are part of the query parameters.

**Comment by jrochkind** [comment]
Hm, is the issue is that your app/users are putting query params in the URL that the controller ignores, but are rendered anyway?  You want to be able to put range-style params in the URL query params that the controller will ignore, and make sure they aren't rendered when the controller is ignoring them?

**Comment by dkinzer** [comment]
>  is the issue is that your app/users are putting query params in the URL that the controller ignores, but are rendered anyway
That is not quite it.  The user herself does not add these query params. The application allows for the user to switch between context.  For example she can search the catalog and limit by range and then switch to an article search. On the article search page we do not apply the facets for the catalog search because the article search has it's own facet fields that do not correspond to the catalog search.

> You want to be able to put range-style params in the URL query params that the controller will ignore, and make sure they aren't rendered when the controller is ignoring them?
Yes, that's the gist of it.

**Comment by dkinzer** [comment]
@jrochkind I should add that the fix I posted will bring this application to be in parity with blacklight.  Blacklight itself already filters out facets per controller.

**Comment by jrochkind** [comment]
That's good to know. 

I'm not really familiar with this code or Blacklight code anymore, are you a blacklight_range_limit committer @dkinzer , and if not do you want to be? 

I am unaware of any particular policies for how committers get added here, but technically I can add you if you're interested.

**Comment by dkinzer** [comment]
@jrochkind thanks.  I am not a committer.  Actually, yes, I'd love to be a committer.

**Comment by dkinzer** [comment]
@jrochkind, that said I don't think it would help move things faster as don't I need approval of my PR before I can commit it?

**Comment by dkinzer** [comment]
I can't reproduce this issue in the latest version of blacklight_range_limit.
