### ISSUE TITLE
Limit Input Field might be to short

### ISSUE THREAD

**Issue by numjcp** [projectblacklight/blacklight_range_limit#17]
Hello, 
The text input field in a facet_limit panel might be longer than the hardcoded 4 maxlength in app/helpers/range_limit_helper.rb: text_field_tag("range...
Even though it's easy to manually change it to suit one's custom need,
wouldn't it be nice if it was parameterized ? Any how any where but not hardcoded ?

Regards

Julien

**Comment by jrochkind** [comment]
Current implementation no longer uses maxlength, no longer relevant.
