### ISSUE TITLE
Support Bootstrap 5

### ISSUE THREAD

**Issue by vstollen** [projectblacklight/blacklight_range_limit#177]
With Blacklight adding Boostrap 5 support in [release v7.20.0](https://github.com/projectblacklight/blacklight/releases/tag/v7.20.0), Bootstrap 5 support for the range limit would be nice as well.

**Comment by jrochkind** [comment]
@vstollen Do you have any sense of what that would look like, what would need to be changed for Bootstrap 5? If you did, or wanted to figure it out, that would probably help make this more likely! Even just sharing what you've noticed not working in Bootstrap 5! 

I think Blacklight currently supports BOTH Bootstrap 4 and 5 somehow, I'm not sure of the details. So I guess this has to be the same.

**Comment by vstollen** [comment]
I'm not sure, if I got everything, but here is what I've found:
1. `sr-only` is now `visually-hidden`
2. `input-group-append` is not needed anymore
3. The close button is broken. The same applies for blacklight itself, so I've created an issue there: https://github.com/projectblacklight/blacklight/issues/2518

In our installation, this meant:
1. Adding `visually-hidden` in:
    -  [line 18 of `range_limit_helper.rb`](https://github.com/projectblacklight/blacklight_range_limit/blob/39888986ea0c5cbcfc60e2e8dd30de9b27d5c0e1/app/helpers/range_limit_helper.rb#L18)
    - [line 18 of `_range_limit_panel.html.erb`](https://github.com/projectblacklight/blacklight_range_limit/blob/8738c83edda0e339ea1e69ec8df69396e85ee041/app/views/blacklight_range_limit/_range_limit_panel.html.erb#L18)
    - [line 64 of `range_limit_slider.js`](https://github.com/projectblacklight/blacklight_range_limit/blob/8738c83edda0e339ea1e69ec8df69396e85ee041/app/assets/javascripts/blacklight_range_limit/range_limit_slider.js#L64)
2. Removing the `div` in [line 64 of `_range_limit_panel.html.erb`](https://github.com/projectblacklight/blacklight_range_limit/blob/8738c83edda0e339ea1e69ec8df69396e85ee041/app/assets/javascripts/blacklight_range_limit/range_limit_slider.js#L64)
3. Applying the fixes proposed in https://github.com/projectblacklight/blacklight/issues/2518 for [lines 3 and 4 in `range_limit_panel.html.erb`](https://github.com/projectblacklight/blacklight_range_limit/blob/8738c83edda0e339ea1e69ec8df69396e85ee041/app/views/blacklight_range_limit/range_limit_panel.html.erb#L3-L4)

The only problem I see in this is, that the `div` I removed in 2. is needed in Bootstrap 4, but seems to break the layout in Bootstrap 5. But maybe there is another solution for that?

I can submit a draft pull request with these changes (maybe except 2.) later.

For reference: [Bootstrap Documentation, Migrating to v5](https://getbootstrap.com/docs/5.1/migration/).

**Comment by vstollen** [comment]
Maybe we could do something for 2. with the `sr-only` and `visually-hidden` classes. 

We could add both versions and `sr-only` would hide the BS4 implementation, `visually-hidden` would hide the BS5 implementation. To not affect accessibility too much, we could add `aria-hidden` to one of the two implementations.

**Comment by jrochkind** [comment]
I am not using Bootstrap 5 yet and haven't looked into it, but I can test any PR you make on my Bootstrap 4 app.

**Comment by jrochkind** [comment]
And in ADDITION, there's a test bug/mis-design, the test somehow doens't accurately capture real behavior.

**Comment by vstollen** [comment]
@jrochkind I've created the PR, but only tested it in our Bootstrap 5 app.

**Comment by jrochkind** [comment]
Thanks @vstollen , linking to the PR is convenient, looks like it's #178. 

I'll test it in my Bootstrap 4-using app presently.
