### ISSUE TITLE
Add support for BC years

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/blacklight_range_limit#18]
We have a few collections that have negative year values (Papyrus Manuscripts) that don't show up properly in the date slider.  We currently remove negative years from the facet that drives the date facet, however we get reports from confused users from time to time.

I am creating this ticket as a place to discuss the feasibility of adding this support to blacklight_range_limit.

**Comment by atz** [comment]
See also #34 for date support overall.

**Comment by starsplatter** [comment]
I've just hit the BC date problem for a couple of collections. Has anyone got any work in progress on this?
