### ISSUE TITLE
Updating begin value increments end value

### ISSUE THREAD

**Issue by barmintor** [projectblacklight/blacklight_range_limit#187]
Reported by Tao Zhao on the Code4Lib Slack:

> A bug with black_range_limit 7.0 plugin:
After I click the button "Limit" to filter the results, and then if I move the start year along the slider, the end year will automatically add by one, i.e., if I search by 2000-2022, then change the 2000 on the left side to be 2005, the year 2022 on the right side will change into 2023, automatically.
Before I do the search using 2000-2022:
![image](https://user-images.githubusercontent.com/119860/169411933-5fb18e08-07b6-4f67-aa69-d70ee40d3892.png)

> Then I change the start year to be 2005, the end year automatically adds by one to be 2023:

![image (1)](https://user-images.githubusercontent.com/119860/169412020-230fc70f-33c8-4483-a37f-2c7250aa2fa7.png)

> I've found some other institutions also had this issue and I wonder if this has been fixed in some later versions. Thanks.

**Comment by barmintor** [comment]
it looks like the change over to the bootstrap slider way back in version 5 (2014) has an alteration of the begin element change handler: https://github.com/projectblacklight/blacklight_range_limit/commit/fa965a73594ac58894add7056235c0895f296a28

if I'm reading that right, it formerly did a insertion-style update of the begin value, but afterwards did an update of the entire value array, the second element of which has been offset by 1 when the slider is constructed, presumably to be inclusive?

**Comment by barmintor** [comment]
Regardless, I am struggling to reproduce the described behavior on the demo app against Blacklight 7.25.2.

**Comment by jrochkind** [comment]
I *did* reproduce on my own app.  Blacklight 7.24.0, blacklight_range_limit 8.1.0. (Have not debugged, just reproduced). 

I can't tag Tao the reporter because this was proxy-reported by barmintor, but Tao, if you see this, it would be helpful to know what version of Blacklight and blacklight_range_limit your report is from.

**Comment by MPLSFedResearchTZ** [comment]
Could you please make corresponding changes in the version 7.0.1 too? The reason is we are working on the Hyrax 2.9.0, which uses blacklight 6. We would really appreciate that if you make patches to Blacklight_range_limit 7.0.1 too to fix the end limit value issue.
