### ISSUE TITLE
Unknown changed to [Missing]

### ISSUE THREAD

**Issue by kosarko** [projectblacklight/blacklight_range_limit#190]
I've noticed this change (the right is https://github.com/projectblacklight/blacklight_range_limit/commit/0a1df5f07a57f1b5b55d61d0e564c53bd17be6c9  and blacklight 7.25.2  the left v8.1.0 and blacklight 7.22.2)
![image](https://user-images.githubusercontent.com/1842385/171874293-d41c8cb9-f118-4912-83bb-b6fd262fa158.png)

Shouldn't the English locale value for key missing be used?
https://github.com/projectblacklight/blacklight_range_limit/blob/31ff89a940810666f3e7feb8698b5d731e67717d/config/locales/blacklight_range_limit.en.yml#L8

**Comment by barmintor** [comment]
It looks like the `blacklight.range_limit.missing` translation is unused after https://github.com/projectblacklight/blacklight_range_limit/commit/a3fd1d412c999939089e11d4a1ed69e2d31e7672 (8.2.0+)

**Comment by jrochkind** [comment]
I think this has been fixed and i18n for "missing" is working again?

**Comment by jrochkind** [comment]
OK right. 

In current blacklight_range_limit, i seem to be able to customize this on a per-facet basis with i18n key

`blacklight.search.fields.facet.missing.[solr_field_name]`

I guess that's how it is now, and, err, intentional?   Should we close this?

**Comment by kosarko** [comment]
sounds good...
