### ISSUE TITLE
`commit` is submitted as query param, but not in blacklight's permitted params list

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_range_limit#196]
When you fill out this form and submit it:

![Screen Shot 2022-07-19 at 3 39 34 PM](https://user-images.githubusercontent.com/149304/179834488-90fae8a5-bce9-487f-bf1e-6f1bd84cc0dc.png)

the "Apply" submit button results in a `&commit=Apply` in your query params. 

The Blacklight (7.28.0) code will use Strong Params to filter params, without having `commit` in it's list of allowed params, eg here: 

https://github.com/projectblacklight/blacklight/blob/v7.28.0/lib/blacklight/parameters.rb#L75

or here:

https://github.com/projectblacklight/blacklight/blob/v7.28.0/lib/blacklight/parameters.rb#L85

By default, in test and development, Rails has `config.action_controller.action_on_unpermitted_parameters == :log`, so either of those lines above will result in your logs having: `Unpermitted parameter: :commit`

In addition, under the default blacklight config where `blacklight_config.filter_search_state_fields == false`, blacklight will [output it's own deprecation warning](https://github.com/projectblacklight/blacklight/blob/v7.28.0/lib/blacklight/parameters.rb#L88), `Deprecation.warn(Blacklight::Parameters, "Blacklight 8 will filter out non-search parameter, including: commit")`.  (I can't actually find that deprecation warning in my logs, but I've confirmed BL is executing that line like so. Not currently shaving the yak to figure out why it isn't in my logs). 

That deprecation warning might lead someone to try to figure out where that is coming from, and conclude that `blacklight_range_limit` is doing something deprecated that needs to be fixed -- but in fact, it's fine if that `commit` param is ignored. 

1. Should blacklight_range_limit on install add `commit` to `config.search_state_fields` fields somehow, to tell blacklight to expect the `commit` param?
   * Is there even a way for an engine/plugin to modify Blacklight `config.search_state_fields` on boot? Or we'd have to generate it somehow or something?
   * I believe this would use the search state filteirng more similar to how Blacklight assumes the use case for StrongParams are, it assumes you aren't using it to intentionally filter things you _expect_, but are listing everything you expect in there, is my impression. 
   * It would avoid the warnings from both Rails and Blacklight "Hey, there's something in here that wasn't permitted"
   * It would allow people to use `config.action_controller.action_on_unpermitted_parameters = :raise` again -- this is not an uncommon thing to do in :test and :development envs. But if blacklight_range_limit intends "oh yeah, we know we're sending :commit but we want it to be filtered out" -- that's incompatible with `:raise` (and really with default `log` too -- if that's the idea perhaps BL docs should tell people to set `config.action_controller.action_on_unpermitted_parameters = false`, and that anything else will give confusing error messsages?
   * ~On the other hand, it means the :commit param would wind up in eg hidden fields trying to serialize the search state too, when it isn't really part of search state.~  This does _not_ seem to be the case, although I'm not sure what's preventing it!  

3. Or we leave it how it is....
   * Trying to use StrongParams to filter "just what we care about for search state", even knowing other things we don't care about for search state (like :commit) are _expected_ in the params, that's not something unexpected, we intend to strip them out
   * Maybe warn people that blacklight is incompatible with `action_on_unpermitted_parameters = :raise`, and really even `action_on_unpermitted_parameters = :log` (the default in log and test) will give misleading results, as we expect there to sometimes be unpermitted params (like :commit) even when everything is working correctly
   * blacklight will still be issuing the somewhat confusing deprecation notice `"Blacklight 8 will filter out non-search parameter, including: commit"`, when in fact there's actually nothing deprecated going on and nothing that can be fixed. 

I wish there was a way to set an individual `ActionController::Parameters` instance to `action_on_unpermitted_parameters = false` to be like "THIS one, we're intentionally using to filter a subset of params from a larger expected param set, and things being filtered out is not an exceptional situation and we don't even want to know about it" -- but there isn't (unless we subclass `ActionController::Parameters` to add one, but that seems like asking for trouble). 

Any thoughts? @cbeer?

**Comment by barmintor** [comment]
I'm adding a commit to my PR in #198 to address this as it pertains specifically to this plugin; there is probably a related issue in the advanced search functionality in Blacklight that the broader conversation would be relevant to as another issue.
