### ISSUE TITLE
asset generator fails on Blacklight 8

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight_range_limit#210]
```
    generate  blacklight_range_limit:assets
       rails  generate blacklight_range_limit:assets
      insert  app/assets/stylesheets/application.css
The file /Users/jcoyne85/workspace/projectblacklight/arclight/.internal_test_app/app/assets/javascripts/application.js does not appear to exist
```

https://github.com/projectblacklight/blacklight_range_limit/blob/main/lib/generators/blacklight_range_limit/assets_generator.rb#L35-L43

This probably happens if the app is not using sprockets for javascript (importmap-rails).

**Comment by jrochkind** [comment]
"bootstrap 8" -- I think is not a thing. Did you mean Blacklight 8.x?  Off the current git head? With Rails... 7.something?

**Comment by jcoyne** [comment]
Yes, this is blacklight as installed from git:
```ruby
gem 'blacklight', github: 'projectblacklight/blacklight'
```

**Comment by jrochkind** [comment]
Thanks! Should the title of this issue say "Blacklight 8" instead of "bootstrap 8"?

**Comment by jcoyne** [comment]
@jrochkind Yes. I updated. Thanks for catching my typo.

**Comment by jrochkind** [comment]
Main branch is currently testing and passing CI with Blacklight 8 under various Rails version and asset pipeline configurations.  I believe this is no longer relevant.
