### ISSUE TITLE
Blacklight.modal is undefined when using Blacklight 8

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight_range_limit#231]
https://github.com/projectblacklight/blacklight_range_limit/blob/567ffafa31142b5d5980791c234b40e2519579a3/app/assets/javascripts/blacklight_range_limit/range_limit_slider.js#L9

https://github.com/projectblacklight/blacklight_range_limit/blob/567ffafa31142b5d5980791c234b40e2519579a3/app/assets/javascripts/blacklight_range_limit/range_limit_distro_facets.js#L35

It should use `Blacklight.Modal.modalSelector` instead

**Comment by saffeullah** [comment]
Were you able to fix this? I am also getting this error and also slider doesnt display in facets

**Comment by saffeullah** [comment]
On the project I am working, we have blacklight (8.0.0) and blacklight_range_limit (8.3.0). The issue is that blacklight range plugin doesnt seem to work. Is there any fix? 
![image](https://github.com/projectblacklight/blacklight_range_limit/assets/41166092/9fa19091-dd52-4efc-9cf9-75304fa7d9ef)

**Comment by jcoyne** [comment]
@saffeullah blacklight_range_limit is not compatible with Blacklight 8.

**Comment by jcoyne** [comment]
I just don't think that anyone has done the work to make this compatible yet.

**Comment by jrochkind** [comment]
Not sure what fixed this, but I believe it is no longer applicable on main branch, and forthcoming 9.0 release.
