### ISSUE TITLE
Blacklight 8, empty range facet shown even for zero results page

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_range_limit#237]
I wanted to reproduce this on a fresh empty app, but I've been unable to create a fresh empty Blacklight 8 app with `blacklight_range_limit`, per #236 

But I do somehow have a branch of my actual app working with `blacklight_range_limit 8.3.0`, `blacklight 8.0.1`, and `rails 7.0.5.1`.  (I am not sure how I got this to work, and have not been able to reproduce in a new blank app!)

Here I have only one problem.  In cases of zero results, when the Blacklight "zero results" message is shown, with Blacklight 7, you get _no_ facets in sidebar -- this is expected. 

In Blacklight 8, my single `blacklight_range_limit` facet is still showing up in sidebar on "zero results" page, and with facet body content that does not make any sense. 

I _believe_ that this is not about anything otherwise custom to my app, and could be reproducible in a stock app -- if anyone can make one!  But these screenshots do show CSS customizations, and the custom "other search tools" static content we've added to our sidebar. 

## Blacklight 7

As expected, no facet content in "zero results" page. ("Other search tools" static content in sidebar is an unrelated customization). As there are no available facets to display at all, we don't even get the "Limit your search" facet section header. 

![Screen Shot 2023-07-05 at 1 30 10 PM](https://github.com/projectblacklight/blacklight_range_limit/assets/149304/70f0c5aa-80b0-4fcf-b908-f41df9f24854)

## Blacklight 8

"Date" is our range facet -- it is showing up in sidebar even in "zero results" page, but with a body that doesn't make any sense. This should not be showing up in a zero results page, as it was not in BL 7. 

![Screen Shot 2023-07-05 at 1 32 34 PM](https://github.com/projectblacklight/blacklight_range_limit/assets/149304/63b38ad0-a250-45d1-ab02-4e889e793002)

**Comment by jrochkind** [comment]
This is related to https://github.com/projectblacklight/blacklight/issues/3054 , but is also it's own problem. 

If the problem were solved so blacklight_range_limit were not rendering a box for an "empty" result set, then you would still get "Limit your search" header because of https://github.com/projectblacklight/blacklight/issues/3054 .  But there's a separate pre-requisite problem here, to make it stop rendering the nonsensical facet box for empty results.

**Comment by jrochkind** [comment]
I think I have a solution, which would be implementing `BlacklightRangeLimit::RangeFacetComponent#render?` as so:

```ruby
    # Don't render if we have no values at all -- most commonly on a zero results page.
    #
    # Normally we'll have at least a min and a max (of values in result set, solr returns),
    # OR a count of objects missing a value -- if we don't have ANY of that, there is literally
    # nothing we can display, and we're probably in a zero results situation.
    def render?
      (@facet_field.min && @facet_field.max) || @facet_field.missing_facet_item
    end
```

But I'm having trouble putting together a PR, because I am having so much trouble with existing tests. 

Trying to run `bundle exec rake ci` I always get 

> Port 8983 is already being used by another process (pid: 26116)

Even though there is in fact no process at 26116.  I feel like I remember there's an unsolved race condition here maybe in `solr_wrapper`, but now I can't find an issue on it. Or maybe it's an unrelated problem. 

If I try to run ONLY the `range_facet_component_spec.rb` specs, to at least get somewhere locally... they ALL fail with:

```ruby
     Failure/Error:
       instance_double(
         BlacklightRangeLimit::FacetFieldPresenter,
         key: 'key',
         html_id: 'id',
         active?: false,
         collapsed?: false,
         in_modal?: false,
         label: 'My facet field',
         selected_range: nil,
         selected_range_facet_item: nil,

       the BlacklightRangeLimit::FacetFieldPresenter class does not implement the instance method: html_id
     # ./spec/components/range_facet_component_spec.rb:15:in `block (2 levels) in <top (required)>'
```

I wonder if tests are actually failing on main in latest Blacklight, maybe this just doesn't really work with BL8 at all currently?

**Comment by seanaery** [comment]
@jrochkind I tried out your proposed solution here (adding `render?` method to `RangeFacetComponent`) and it works great. So if those test issues you encountered last year are resolved and you're able to get this into a PR, I think it'd be a nice addition for version 9.

**Comment by jrochkind** [comment]
Oh interesting! if you already tried it out, any interest in doing the PR @seanaery ?  I guess it would need a spec too. 

I've got a couple other bugs I'd like to attack still too.

**Comment by seanaery** [comment]
Sure, I'm glad to do it -- just didn't want to take credit for your work. I'll likely be able to get to this tomorrow.
