### ISSUE TITLE
Multivalued fields?

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight_range_limit#26]
Would anyone like to see this as an added feature?

We are currently using blacklight range limit in GeoBlacklight and have integer year fields which seem to be causing an error with this plugin. Would others be interested in seeing that functionality added?

https://github.com/geoblacklight/geoblacklight/issues/263

**Comment by jrochkind** [comment]
Hm, when I wrote the original implementation, I had supporting multi-valued fields in mind.  It probably shouldn't be that hard to fix. I do not have a use case for it myself at MPOW though.  

If you can make a failing test (which I realize is a non-trivial task for several reasons), I can probably find time to make the test pass -- but I suspect if you can make a failing test, the solution will probably present itself to you.

**Comment by mejackreed** [comment]
This turned out not to be the issue. `0` values were causing javascript errors as zero evaluates to false in javascript.  Fixed in #27

**Comment by jrochkind** [comment]
@mejackreed++ thanks!
