### ISSUE TITLE
Enable bypassing the assets generator

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/blacklight_range_limit#286]
It'd be really valuable to add a `--skip-assets` option to the `InstallGenerator`. This option [exists in Blacklight core](https://github.com/projectblacklight/blacklight/blob/main/lib/generators/blacklight/install_generator.rb#L15), and I have found it essential in cases where my application's Javascript approach doesn't quite match the assumptions made by the generator and needs more nuanced/manual setup (e.g., applications that are still using Sprockets for JS).

E.g., currently if running `generate 'blacklight_range_limit:install'` in a Blacklight 8 application that began with `generate 'blacklight:install', '--skip-assets'` & `generate 'blacklight:assets:sprockets'` I get this error, as I have neither `importmap-rails` nor `package.json`. 

```
info  =================================
        info  Installing Blacklight Range Limit
        info  =================================
    generate  blacklight_range_limit:install
       rails  generate blacklight_range_limit:install 
    generate  blacklight_range_limit:assets
       rails  generate blacklight_range_limit:assets 
/gems/ruby/3.3.0/gems/blacklight_range_limit-9.0.0.beta1/lib/generators/blacklight_range_limit/assets_generator.rb:37:in `set_default_options': Could not identify asset_delivery_mode, try supplying --asset-delivery-mode=[importmap-rails|yarn-package] (ArgumentError)

          raise ArgumentError.new("Could not identify asset_delivery_mode, try supplying --asset-delivery-mode=[importmap-rails|yarn-package]")
```

**Comment by jrochkind** [comment]
Yes, we need this, I'll try to get to it, although suddenly got kind of overwhelmed with tasks today!
