### ISSUE TITLE
Test jetty solr severely handicapped

### ISSUE THREAD

**Issue by atz** [projectblacklight/blacklight_range_limit#35]
The jetty/solr that gets spun up is too limited to allow much inspection.  You might consider this an upstream (blacklight) problem.  I'd agree, but the scope I care about right now is here.

### Examples 
With no query at all, it works:
http://localhost:8888/solr/blacklight-core/select?wt=json&indent=true
```json
{
  "responseHeader":{
    "status":0,
    "QTime":2,
    "params":{
      "indent":"true",
      "wt":"json"}},
  "response":{"numFound":31,"start":0,"maxScore":1.0,"docs":[ // ...
   ]}
}
```
You get facet_counts and documents.  But try to q=*anything* and you get nothing, including:
- `http://localhost:8888/solr/blacklight-core/select?q=pub_date:1998&wt=json&indent=true`
- `http://localhost:8888/solr/blacklight-core/select?q=id:*&wt=json&indent=true`
- `http://localhost:8888/solr/blacklight-core/select?q=*:*&wt=json&indent=true`

Then these work:
- `http://localhost:8888/solr/blacklight-core/select?wt=json&indent=true&defType=dismax&q.alt=pub_date%3A1998`
- `http://localhost:8888/solr/blacklight-core/select?wt=json&indent=true&defType=dismax&q.alt=pub_date%3A%5B1990+TO+2000%5D `
- `http://localhost:8888/solr/blacklight-core/select?wt=json&indent=true&q.alt=id%3A* `
- `http://localhost:8888/solr/blacklight-core/select?wt=json&indent=true&q.alt=*%3A* `

There is no `select` handler defined, so presumably these are falling through to `search`.  And for some reason you are required to use `q.alt` instead of `q`.  That is weird.

Reasonable default test solr config should be usable in admin panel and on command line without oddities like that.

**Comment by cbeer** [comment]
Like I mentioned earlier, the `search` handler is probably using `dismax`, not `lucene`, query parsing. `q.alt` uses `lucene` query parsing.

This project, along with a bunch of other blacklight gems, are just using the default configuration we have in https://github.com/projectblacklight/blacklight-jetty. I doubt anyone has strong opinions about what's in there, just that it works with our test suite(s).

**Comment by atz** [comment]
You are right, it is using dismax: https://github.com/projectblacklight/blacklight-jetty/blob/master/solr/blacklight-core/conf/solrconfig.xml#L74-L78

My mistake.
