### ISSUE TITLE
range limit search constraints should show in page title

### ISSUE THREAD

**Issue by ebenenglish** [projectblacklight/blacklight_range_limit#49]
When I am on the search results page (catalog#index)
And I modify the values of the range limit input(s) and click 'Limit'
I should see the range limit search constraints in the page title in the browser window

`Blacklight::CatalogHelperBehavior#render_search_to_page_title` (from projectblacklight/blacklight@47eab51) adds functionality to display search constraints in the page title on catalog#index views. However, range limit search constraints are not displayed, since there is no provision in that method to display them.

**Comment by barmintor** [comment]
The refactor to use filter fields fixes this on the plugin side, but there is an [issue in Blacklight](https://github.com/projectblacklight/blacklight/issues/2707). Closing this ticket, as there's not anything more for the plugin to do.
