### ISSUE TITLE
Sprockets require vs. SCSS @import

### ISSUE THREAD

**Issue by atz** [projectblacklight/blacklight_range_limit#55]
https://github.com/rails/sass-rails#important-note

> Sprockets provides some directives that are placed inside of comments called require, require_tree, and require_self. DO NOT USE THEM IN YOUR SASS/SCSS FILES. They are very primitive and do not work well with Sass files. Instead, use Sass's native `@import` directive which sass-rails has customized to integrate with the conventions of your Rails projects.

The `blacklight_range_limit` generator will insert `require` statements in SCSS files.  Apparently, this is to be avoided.

**Comment by cbeer** [comment]
👍 I think we've fixed this in blacklight, and it would be great if we fixed this everywhere.

**Comment by jrochkind** [comment]
No longer relevant to current main branch, which no longer does sprockets requires at all.
