### ISSUE TITLE
Release 6.1.2?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_range_limit#62]
Can I release a 6.1.2 with the bugfix from #61? That's the only thing in master that isn't in 6.1.1

https://github.com/projectblacklight/blacklight_range_limit/compare/v6.1.1...master

@mejackreed ? Not sure who else is if anyone is an informal maintainer of this gem, or would otherwise want to be consulted on a release decision?  If I don't hear back by, um, tomorrow I guess, I'll go ahead?

**Comment by mejackreed** [comment]
I say ship it 👍

**Comment by jrochkind** [comment]
released 6.1.2
