### ISSUE TITLE
Slider does not work if segments are disabled

### ISSUE THREAD

**Issue by mohideen** [projectblacklight/blacklight_range_limit#73]
When the segments chart is enabled, the slider works correctly updating the value in the text boxes above. But, when segments are set to false in the configuration, slider changes does update the text box.
segments: false
![not_working](https://user-images.githubusercontent.com/1703851/33859511-430c01a4-dea2-11e7-8a6b-154f930a4706.gif)

segments:true
![working](https://user-images.githubusercontent.com/1703851/33859512-43175d2e-dea2-11e7-9765-2dea0b0b2bf4.gif)

**Comment by mohideen** [comment]
Created a PR to fix this.
https://github.com/projectblacklight/blacklight_range_limit/pull/75

**Comment by mohideen** [comment]
@tampakis Thanks for merging in the PR. Is there any new release/tag scheduled for the plugin? Otherwise, I will update our Gemfile to use Github + ref.

Otherwise, I guess this issue can be closed.

**Comment by tampakis** [comment]
I just released version 6.3.2
