### ISSUE TITLE
Support blacklight 7

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight_range_limit#82]
We need to remove:

the `require` from
https://github.com/projectblacklight/blacklight_range_limit/blob/master/app/assets/javascripts/blacklight_range_limit/range_limit_slider.js#L2

**Comment by anarchivist** [comment]
There's also an older `blacklight-7` branch which is out of date with `master`. We should look at that at some point soon.

**Comment by mejackreed** [comment]
Yep I think arclight is using that blacklight-7 branch.

**Comment by mejackreed** [comment]
I think we can close this now, with the latest RC and recent PR's
