### ISSUE TITLE
facet_limit instead of facet-limit

### ISSUE THREAD

**Issue by hudajkhan** [projectblacklight/blacklight_range_limit#95]
Hi! I'm not sure if this is the best way to ask this question. but as we're trying to use the range limit slider, we've noticed that with our code upgraded to using Blacklight 7, our configuration for the slider doesn't seem to be applied.  What appears to be happening is that this code: https://github.com/projectblacklight/blacklight_range_limit/blob/fa8d106ce921f9e398032e02ad7dbfaeac76c53a/app/assets/javascripts/blacklight_range_limit/range_limit_distro_facets.js#L182 is looking for .facet_limit whereas facets are being rendered with .facet-limit (see https://github.com/projectblacklight/blacklight/blob/master/app/views/catalog/_facet_layout.html.erb ) i.e. hyphen instead of underscore.

**Comment by mejackreed** [comment]
Resolved in #145 shipped in v7.7.0
