### ISSUE TITLE
`tether` requirement?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_range_limit#97]
The blacklight_range_limit generator adds a `//= require tether` to your application.js. 

This appears to have been added in commit c9275b, as part of many other changes to "Update to Blacklight 7", with no further comments. (Not sure if the tether dependency actually pre-dates this, but was just moved around?). 

I can't find any use of `tether` in blacklight_range_limit JS, or other documentation of what it's for and why it's needed. 

Can anyone shed some light?

If we document what it's for and how it's used, we'll have some chance of recognizing if it _no longer becomes_ necessary in the future, or has another better alternative. Try to avoid the risk of it staying in the codebase forever that it's generated into local app, when not necessarily needed/optimal, because nobody remembers what it's for.

**Comment by mejackreed** [comment]
Its possible that it may not be needed anymore. I believe BS4-alpha had a requirement for Tether to use Popper.js. Not sure if this is necessary anymore.

**Comment by jcoyne** [comment]
Looks like when 4.0 beta was released they fixed that: https://github.com/twbs/bootstrap/commit/c4b4d534a4e935db72a37b54f0f41f4dba4c83de

**Comment by jrochkind** [comment]
Yeah, I just got back to this too. I think some early BS4 betas required tether. But they switched to `popper` instead of `tether` -- I think maybe even before BS 4.0.0 final?

https://github.com/twbs/bootstrap/pull/22444

A generated Blacklight app already has a generated `require popper` in it's application.js. https://github.com/projectblacklight/blacklight/blob/55e748dd3465b9e2781d4def04b912fcbfb1b231/lib/generators/blacklight/assets_generator.rb

When you run the blacklight_range_limit installer, it adds an additional `require tether`. 

I believe the require tether is unnecessary. If I remove it, my demo app still works fine. (On the other hand, if I remove `require popper`, I get a message in console, `Bootstrap's tooltips require Popper.js `, and indeed Bootstrap tooltips -- including the ones blacklight_range_limit tries to use -- don't work). 

I believe we should remove the line from the blacklight_range_limit generator/installer that adds `require 'tether'`, and count on the host app to have it already (as it will if it ran the Blacklight generator, and didn't remove what Blacklight added -- but at any rate, blacklight_range_limit isn't adding the actually necessary popper for BS4 already anyway). 

Make sense, I'll prepare a PR?
